// Shared finish panels data — used by finishes page and product page texture selector
export const panelsData = [
  // METALLIC
  { name: "Spectrum Light", code: "6023", category: "metallic", img: "/images/panels/6023-spectrum-light.jpg" },
  { name: "Spectrum Rose", code: "6026", category: "metallic", img: "/images/panels/6026-spectrum-rose.jpg" },
  { name: "Metallic Inox", code: "300", category: "metallic", img: "/images/panels/300-metallic-inox.jpg" },
  { name: "Matt Picasso Inox", code: "394", category: "metallic", img: "/images/panels/394-matt-picasso-inox.jpg" },
  { name: "Matt Picasso Gold", code: "395", category: "metallic", img: "/images/panels/395-matt-picasso-gold.jpg" },
  { name: "HG Metallic Anthracite", code: "608", category: "metallic", img: "/images/panels/608-hg-metallic-anthracite.jpg" },

  // HIGH GLOSS
  { name: "HG Night Blue", code: "4003", category: "high-gloss", img: "/images/panels/4003-hg-night-blue.jpg" },
  { name: "HG White", code: "601", category: "high-gloss", img: "/images/panels/601-hg-white.jpg" },
  { name: "HG Black", code: "6002", category: "high-gloss", img: "/images/panels/6002-hg-black.jpg" },
  { name: "HG Light Cream", code: "6011", category: "high-gloss", img: "/images/panels/6011-hg-light-cream.jpg" },
  { name: "HG Pebble Grey", code: "6012", category: "high-gloss", img: "/images/panels/6012-hg-pebble-grey.jpg" },
  { name: "HG Light Grey", code: "6013", category: "high-gloss", img: "/images/panels/6013-hg-light-grey.jpg" },
  { name: "HG Grey", code: "6014", category: "high-gloss", img: "/images/panels/6014-hg-grey.jpg" },
  { name: "HG Shark Tail", code: "6015", category: "high-gloss", img: "/images/panels/6015-hg-shark-tail.jpg" },
  { name: "HG Gentle Grey", code: "6016", category: "high-gloss", img: "/images/panels/6016-hg-gentle-grey.jpg" },
  { name: "HG Porte Pearl White", code: "6004", category: "high-gloss", img: "/images/panels/6004-hg-porte-pearl-white.jpg" },
  { name: "HG Galaxy White", code: "670", category: "high-gloss", img: "/images/panels/670-hg-galaxy-white.jpg" },
  { name: "HG Metallic Elm", code: "603", category: "high-gloss", img: "/images/panels/603-hg-metallic-elm.jpg" },
  { name: "HG Milano Walnut", code: "627", category: "high-gloss", img: "/images/panels/627-hg-milano-walnut.jpg" },
  { name: "HG Line Pearl", code: "675", category: "high-gloss", img: "/images/panels/675-hg-line-pearl.jpg" },
  { name: "HG White Sahara", code: "662", category: "high-gloss", img: "/images/panels/662-hg-white-sahara.jpg" },

  // SOFT TOUCH
  { name: "Soft Touch Black", code: "723", category: "soft-touch", img: "/images/panels/723-soft-touch-black.jpg" },
  { name: "Soft Touch White", code: "734", category: "soft-touch", img: "/images/panels/734-soft-touch-white.jpg" },
  { name: "Soft Touch Storm Grey", code: "726", category: "soft-touch", img: "/images/panels/726-soft-touch-storm-grey.jpg" },
  { name: "Soft Touch Stone Grey", code: "728", category: "soft-touch", img: "/images/panels/728-soft-touch-stone-grey.jpg" },
  { name: "Soft Touch New Grey", code: "729", category: "soft-touch", img: "/images/panels/729-soft-touch-new-grey.jpg" },
  { name: "Soft Touch Relax Green", code: "735", category: "soft-touch", img: "/images/panels/735-soft-touch-relax-green.jpg" },
  { name: "Soft Touch Ocean Blue", code: "736", category: "soft-touch", img: "/images/panels/736-soft-touch-ocean-blue.jpg" },
  { name: "Soft Touch Sienna Wood", code: "737", category: "soft-touch", img: "/images/panels/737-soft-touch-sienna-wood.jpg" },
  { name: "Soft Touch Clay", code: "738", category: "soft-touch", img: "/images/panels/738-soft-touch-clay.jpg" },
  { name: "Super Matt Light Cream", code: "398", category: "soft-touch", img: "/images/panels/398-supermatt-light-cream.jpg" },
  { name: "Super Matt Pebble Grey", code: "399", category: "soft-touch", img: "/images/panels/399-supermatt-pebble-grey.jpg" },
  { name: "Super Matt Light Grey", code: "3001", category: "soft-touch", img: "/images/panels/3001-supermatt-light-grey.jpg" },
  { name: "Super Matt Dark Grey", code: "3002", category: "soft-touch", img: "/images/panels/3002-supermatt-dark-grey.jpg" },
  { name: "Super Matt Night Blue", code: "3003", category: "soft-touch", img: "/images/panels/3003-supermatt-night-blue.jpg" },
  { name: "Matt Galaxy White", code: "3006", category: "soft-touch", img: "/images/panels/3006-matt-galaxy-white.jpg" },
  { name: "Matt Galaxy Black", code: "3009", category: "soft-touch", img: "/images/panels/3009-matt-galaxy-black.jpg" },

  // TEXTURED
  { name: "Matt Light Walnut", code: "239", category: "textured", img: "/images/panels/239-matt-light-walnut.jpg" },
  { name: "Matt Teak", code: "248", category: "textured", img: "/images/panels/248-matt-teak.jpg" },
  { name: "Toledo Light Wood", code: "388", category: "textured", img: "/images/panels/388-toledo-light-wood.jpg" },
  { name: "Toledo Dark Wood", code: "389", category: "textured", img: "/images/panels/389-toledo-dark-wood.jpg" },
  { name: "Matt Natural Touch Oak", code: "397", category: "textured", img: "/images/panels/397-matt-natural-touch-oak.jpg" },
  { name: "Matt Texas Oak", code: "3037", category: "textured", img: "/images/panels/3037-matt-texas-oak.jpg" },
  { name: "Matt Vermont Oak", code: "3038", category: "textured", img: "/images/panels/3038-matt-vermont-oak.jpg" },
  { name: "Matt Delphi Oak", code: "3039", category: "textured", img: "/images/panels/3039-matt-delphi-oak.jpg" },
  { name: "Matt Peru Oak", code: "3041", category: "textured", img: "/images/panels/3041-matt-peru-oak.jpg" },
  { name: "Matt Akra Oak", code: "3042", category: "textured", img: "/images/panels/3042-matt-akra-oak.jpg" },
  { name: "Classic Oak", code: "3076", category: "textured", img: "/images/panels/3076-classic-oak.jpg" },
  { name: "Tokyo White", code: "3075", category: "textured", img: "/images/panels/3075-tokyo-white.jpg" },
  { name: "Tokyo Grey", code: "3074", category: "textured", img: "/images/panels/3074-tokyo-grey.jpg" },
  { name: "Matt Cashmere White", code: "383", category: "textured", img: "/images/panels/383-matt-cashmere-white.jpg" },
  { name: "Matt Cashmere Gold", code: "384", category: "textured", img: "/images/panels/384-matt-cashmere-gold.jpg" },
  { name: "Matt Cashmere Grey", code: "387", category: "textured", img: "/images/panels/387-matt-cashmere-grey.jpg" },

  // ACRYLIC
  { name: "Acrylic White", code: "8015", category: "acrylic", img: "/images/panels/8015-acrylic-white.jpg" },
  { name: "Bright White Acrylic", code: "8011", category: "acrylic", img: "/images/panels/8011-bright-white-acrylic.jpg" },

  // SUPRAMAT
  { name: "Supramat Sonara", code: "3094", category: "supramat", img: "/images/panels/3094-supramat-sonara.jpg" },
  { name: "Supramat Havana Coffee", code: "3096", category: "supramat", img: "/images/panels/3096-supramat-havana-coffee.jpg" },
  { name: "Supramat Safari Grey", code: "3020", category: "supramat", img: "/images/panels/3020-supramat-safari-grey.jpg" },
  { name: "Supramat Royal Grey", code: "3022", category: "supramat", img: "/images/panels/3022-supramat-royal-grey.jpg" },
  { name: "Supramat London Blues", code: "3011", category: "supramat", img: "/images/panels/3011-supramat-london-blues.jpg" },
  { name: "Supramat Macaron Green", code: "3015", category: "supramat", img: "/images/panels/3015-supramat-macaron-green.jpg" },
  { name: "Supramat Pink Daisy", code: "3016", category: "supramat", img: "/images/panels/3016-supramat-pink-daisy.jpg" },
  { name: "Supramat Timeless Grey", code: "3017", category: "supramat", img: "/images/panels/3017-supramat-timeless-grey.jpg" },
  { name: "Supramat Moonlight", code: "3018", category: "supramat", img: "/images/panels/3018-supramat-moonlight.jpg" },
  { name: "Supramat Sahara Cream", code: "3019", category: "supramat", img: "/images/panels/3019-supramat-sahara-cream.jpg" },
  { name: "Supramat Ice Grey", code: "3021", category: "supramat", img: "/images/panels/3021-supramat-ice-grey.jpg" },
  { name: "Supramat Dolphin Grey", code: "3023", category: "supramat", img: "/images/panels/3023-supramat-dolphin-grey.jpg" },
  { name: "Supramat Pebble Grey", code: "3024", category: "supramat", img: "/images/panels/3024-supramat-pebble-grey.jpg" },
  { name: "Supramat Bitter", code: "3025", category: "supramat", img: "/images/panels/3025-supramat-bitter.jpg" },
  { name: "Supramat Rustic Red", code: "3026", category: "supramat", img: "/images/panels/3026-supramat-rustic-red.jpg" },
  { name: "Supramat Forest Green", code: "3027", category: "supramat", img: "/images/panels/3027-supramat-forest-green.jpg" },
  { name: "Supramat Glamorous Pacific", code: "3029", category: "supramat", img: "/images/panels/3029-supramat-glamorous-pacific.jpg" },

  // 3P PANEL
  { name: "Caretta Green", code: "3051", category: "3p-panel", img: "/images/panels/3051-caretta-green.jpg" },
  { name: "Timber Light", code: "3061", category: "3p-panel", img: "/images/panels/3061-timber-light.jpg" },
  { name: "Timber Grey", code: "3071", category: "3p-panel", img: "/images/panels/3071-timber-grey.jpg" },
  { name: "Croco Blue", code: "3062", category: "3p-panel", img: "/images/panels/3062-croco-blue.jpg" },
  { name: "Croco Grey", code: "3063", category: "3p-panel", img: "/images/panels/3063-croco-grey.jpg" },
  { name: "Croco Cream", code: "3064", category: "3p-panel", img: "/images/panels/3064-croco-cream.jpg" },
  { name: "Textile Light", code: "3059", category: "3p-panel", img: "/images/panels/3059-textile-light.jpg" },
  { name: "Textile Vison", code: "3060", category: "3p-panel", img: "/images/panels/3060-textile-vison.jpg" },
  { name: "Slate Cream", code: "3056", category: "3p-panel", img: "/images/panels/3056-slate-cream.jpg" },
  { name: "Slate Grey", code: "3057", category: "3p-panel", img: "/images/panels/3057-slate-grey.jpg" },
  { name: "Slate Coffee", code: "3058", category: "3p-panel", img: "/images/panels/3058-slate-coffee.jpg" },
  { name: "Slate Beige", code: "3069", category: "3p-panel", img: "/images/panels/3069-slate-beige.jpg" },
];

export const categoryLabelsFinishes = {
  'metallic': 'Metallic',
  'high-gloss': 'High Gloss',
  'soft-touch': 'Soft Touch',
  'textured': 'Textured',
  'acrylic': 'Acrylic',
  'supramat': 'Supramat',
  '3p-panel': '3P Panel',
};
